### ISSUE TITLE
Investigate ruff as faster flake8 + isort alternative

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-tooling#10]
https://pypi.org/project/ruff/

> Ruff aims to be orders of magnitude faster than alternative tools while integrating more functionality behind a single, common interface.
> 
> Ruff can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [yesqa](https://github.com/asottile/yesqa), [eradicate](https://pypi.org/project/eradicate/), [pyupgrade](https://pypi.org/project/pyupgrade/), and [autoflake](https://pypi.org/project/autoflake/), all while executing tens or hundreds of times faster than any individual tool.

**Comment by legoktm** [comment]
I'm blown away by how fast and good ruff is. Like, there are a bunch of testimonals about how it's so fast people think it can't be running, but it is. It covers the entire SecureDrop server repo in **78ms**!!!

It is incredibly trivial to enable/disable rules, the documentation is pretty clear on what each rule does and https://beta.ruff.rs/docs/rules/ contains all of them.

The fact that it also incorporates other tools that we probably should've been using but added more overhead to set up is *chef's kiss*.

Specifically, https://beta.ruff.rs/docs/rules/#flake8-gettext-int - would catch the stuff we outlined in https://github.com/freedomofpress/securedrop/issues/6380#issuecomment-1135234545

**Comment by legoktm** [comment]
I should also add that it's incredibly frustrating to see a tool automatically fix errors that you've spent hours of your life doing by hand <3

Here's the pyproject.toml I have so far:
```toml

[project]
name = "securedrop"
requires-python = ">=3.8"

[tool.ruff]
line-length = 100
select = [
    "E",
    "F",
    "INT",
    "PIE",
    "PL",
    "PT",
    "PYI",
    "RET",
    "SIM",
    "UP",
    "W",
]
ignore = [
    # incompatible with sqlalchemy https://github.com/astral-sh/ruff/issues/4560
    "E712",
    # doesn't understand flask.abort() (TODO: file upstream)
    "RET503",
    # Find contextlib.suppress() is harder to read
    "SIM105",
    # Find ternary statements harder to read
    "SIM108",
]
```

Notably this does not enable ruff's isort replacement nor the bugbear plugin.

The isort implementation is sorting things out of the box differently, I haven't tracked down why yet. I'm kind of thinking this might be a good time to fix the project layout and use standard imports instead of our `sys.path.append()` hacks.

I didn't enable bugbear yet because there was a lot and I needed more time to go through them all.

**Comment by legoktm** [comment]
The main "downside" of ruff is that it is not extensible - unlike flake8 it does not support plugins, all lints and fixes need to be maintained in-tree. A monolithic linter may be a problem in the long-run, depending on what kind of community grows around it. I personally welcome a monolithic linter just because Python tooling is a huge mess and real consolidation of them (not just flake8 wrapping pycodestyle + pyflakes) is genuinely simplifying things.

Also SecureDrop never used any flake8 plugins in the first place (though we likely should have) so we're not losing any functionality here.

**Comment by legoktm** [comment]
I got isort to match our current setup with:
```toml
[tool.ruff.isort]
# ruff's isort is smart enough to know these are first party, but let's treat
# them as third-party to match O.G. isort until we fix our package layout
known-third-party = ["journalist_app", "management", "source_app", "tests"]
```

It also has some support for `bandit` - https://beta.ruff.rs/docs/rules/#flake8-bandit-s, still need to explore how comprehensive it is.

**Comment by legoktm** [comment]
I've marked https://github.com/freedomofpress/securedrop/pull/6885 as ready for review.

**Comment by rocodes** [comment]
Now that https://github.com/freedomofpress/securedrop/pull/6885 is in, what would you think is a good next step? (Would you like someone to prepare corresponding PRs in other repos, would you like to stick to the sd repo and look at things like bandit support?)

**Comment by legoktm** [comment]
I think we can just copy the ruff config from securedrop's pyproject.toml today (whether or not it includes bandit) and as we keep adding new plugins, we can gradually add it to the other projects too. And maybe create tickets here for tracking the spread of ruff / new ruff plugins to all our repos.

**Comment by legoktm** [comment]
Gonna close this since we're pretty far down the ruff road already and I don't think there are any follow-ups left.
