### ISSUE TITLE
Migrate SDW component repositories CI to GitHub Actions

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-tooling#12]
Likely after we make more progress on #5.

Debian packages:
- https://github.com/freedomofpress/securedrop-proxy
- https://github.com/freedomofpress/securedrop-log
- https://github.com/freedomofpress/securedrop-export
- https://github.com/freedomofpress/securedrop-client

RPM packages:
- https://github.com/freedomofpress/securedrop-updater
- https://github.com/freedomofpress/securedrop-workstation

**Comment by zenmonkeykstop** [comment]
Repo consolidation has largely invalidated this - will cover as part of other CI issues/epics.
